<?php

namespace Database\Seeders;

use App\Models\Ponpes;
use Faker\Factory as Faker;
use Illuminate\Database\Seeder;

class PonpesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Ponpes::factory()->count(10)->create();
        $faker = Faker::create();

        $category = ['Pesantren Salafiyah (Tradisional)', 'Pesantren Khalafiyah (Modern)', 'Pesantren Kombinasi'];

        $ponpes = [
            // contoh
            [
                'user_id' => 2,
                'nspp' => '510000000000',
                'name' => 'Contoh Pesantren',
                'category' => 'Pesantren Kombinasi',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,

                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Limpung',
                'postal_code' => 51271,
                'address' => 'Belum diisi',
                'latitude' => -6.993116719850695,
                'longitude' => 109.92871970193553,
                'status' => 'active',
            ],

            // Entry 1 (Daarul Ishlah)
            [
                'nspp' => '510033250002',
                'name' => 'Daarul Ishlah',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '2.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bandar',
                'postal_code' => 51254,
                'address' => 'Jl. Puncak Km.4 RT.003/003',
                'latitude' => -7.090687277305945,
                'longitude' => 109.78335146620175,
                'status' => 'active',
            ],

            // Entry 2 (Nurul Hidayah)
            [
                'nspp' => '510033250003',
                'name' => 'Nurul Hidayah',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '3.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bandar',
                'postal_code' => 51254,
                'address' => 'Desa Sidayu',
                'latitude' => -7.043354948457385,
                'longitude' => 109.81081745435844,
                'status' => 'active',
            ],

            // Entry 3 (WALI BONJOR)
            [
                'nspp' => '510033250051',
                'name' => 'WALI BONJOR',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '4.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bandar',
                'postal_code' => 51254,
                'address' => 'Belum diisi', // Address is missing in the provided data
                'latitude' => -7.052888915251772,
                'longitude' => 109.81777296946223,
                'status' => 'active',
            ],

            [
                'nspp' => '510033250057',
                'name' => 'DHIYAUL FALAH',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '5.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bandar',
                'postal_code' => 51254,
                'address' => 'Belum diisi', // Address is missing in the provided data
                'latitude' => -7.021480908394185,
                'longitude' => 109.79817869269907,
                'status' => 'active',
            ],

            // Entry 5 (Khafidul Qur`an)
            // [
            //     'nspp' => '510033250060',
            //     'name' => 'Khafidul Qur`an',
            //     'category' => 'Pesantren Salafiyah (Tradisional)',
            //     'phone_number' => $faker->phoneNumber(12),
            //     'website' => 'www.' . $faker->word(7) . '.com',
            //     'email' => $faker->email,
            //        'standing_date' => $faker->date,
            //     'pimpinan' => 'Belum diisi',
            //     'surface_area' => $faker->randomNumber(4, true),
            //     'building_area' => $faker->randomNumber(4, true),
            //     'city' => 'Batang',
            //     'subdistrict' => 'Bandar',
            //     'postal_code' => 51254,
            //     'address' => 'Ds Sidayu',
            //     'latitude' => null,
            //     'longitude' => null,
            //     'status' => 'active',
            // ],

            // Entry 6 (BAHRIYYATUL ASROR)
            [
                'nspp' => '510033250067',
                'name' => 'BAHRIYYATUL ASROR',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '6.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bandar',
                'postal_code' => 51254,
                'address' => 'Belum diisi', // Address is missing in the provided data
                'latitude' => -7.053617266399312,
                'longitude' => 109.80621284798697,
                'status' => 'active',
            ],

            // Entry 7 (NURUL BURHAN)
            [
                'nspp' => '510033250075',
                'name' => 'NURUL BURHAN',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '7.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bandar',
                'postal_code' => 51254,
                'address' => 'Belum diisi', // Address is missing in the provided data
                'latitude' => -6.9688599203941335,
                'longitude' => 109.77599083416303,
                'status' => 'active',
            ],

            // Entry 8 (AL KHAIDAR)
            [
                'nspp' => '510033250092',
                'name' => 'AL KHAIDAR',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '8.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bandar',
                'postal_code' => 51254,
                'address' => 'Belum diisi', // Address is missing in the provided data
                'latitude' => -7.029326385939575,
                'longitude' => 109.80426863210252,
                'status' => 'active',
            ],

            // Entry 9 (PONDOK MODERN TAZAKKA)
            [
                'nspp' => '510033250110',
                'name' => 'PONDOK MODERN TAZAKKA',
                'category' => 'Pesantren Khalafiyah (Modern)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '9.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bandar',
                'postal_code' => 51254,
                'address' => 'Belum diisi', // Address is missing in the provided data
                'latitude' => -7.0403953296692166,
                'longitude' => 109.80377613821248,
                'status' => 'active',
            ],

            // Entry 10 (Roudlotut Tholibin)
            [
                'nspp' => '510033250126',
                'name' => 'Roudlotut Tholibin',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '10.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bandar',
                'postal_code' => 51254,
                'address' => 'Jl. Raya Pesalakan Bandar', // Address is provided
                'latitude' => -7026931793198360, // Fix this value if it's incorrect
                'longitude' => 109.77769824244000, // Fix this value if it's incorrect
                'status' => 'active',
            ],

            // Entry 11 (Al Minhaj)
            [
                'nspp' => '510333250091',
                'name' => 'Al Minhaj',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '11.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bandar',
                'postal_code' => 51254,
                'address' => 'Ds. Wonosegoro', // Address is provided
                'latitude' => -6.984899076378393,
                'longitude' => 109.79115142572337,
                'status' => 'active',
            ],

            // Entry 12 (PONDOK PESANTREN TERPADU DARUL HIKMAH)
            [
                'nspp' => '512333250053',
                'name' => 'PONDOK PESANTREN TERPADU DARUL HIKMAH',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '12.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bandar',
                'postal_code' => 51254,
                'address' => 'Belum diisi', // Address is missing in the provided data
                'latitude' => -7.067537895661881,
                'longitude' => 109.79098557682707,
                'status' => 'active',
            ],

            // Entry 13 (MIFTAHUL ULUM)
            [
                'nspp' => '510033250010',
                'name' => 'MIFTAHUL ULUM',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '13.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Banyuputih',
                'postal_code' => 51271,
                'address' => 'JL. CERMAI',
                'latitude' => -6.960889911258614,
                'longitude' => 109.96309741526576,
                'status' => 'active',
            ],

            // Entry 16 (Roudlotussalam)
            [
                'nspp' => '510033250112',
                'name' => 'Roudlotussalam',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Banyuputih',
                'postal_code' => 51271,
                'address' => 'Dk Luwung', // Address is provided
                'latitude' => -6.9887807113130735,
                'longitude' => 109.9280270622116,
                'status' => 'active',
            ],

            // Entry 17 (An Nahdliyyah)
            [
                'nspp' => '510033250117',
                'name' => 'An Nahdliyyah',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '15.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Banyuputih',
                'postal_code' => 51271,
                'address' => 'Banyuputih', // Address is provided
                'latitude' => -6.975489983780026,
                'longitude' => 109.92672135863782,
                'status' => 'active',
            ],

            // Entry 18 (Al Istiqomah)
            [
                'nspp' => '510333250071',
                'name' => 'Al Istiqomah',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '16.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Banyuputih',
                'postal_code' => 51271,
                'address' => 'Kp. Blimbing Rt. 01 Rw. 02 Desa Luwung 51271', // Address is provided
                'latitude' => -6.984469709498073,
                'longitude' => 109.93296208708696,
                'status' => 'active',
            ],

            // //   Entry 19 (Sabilunnajah)
            // [
            //     'nspp' => '510333250085',
            //     'name' => 'Sabilunnajah',
            //     'category' => 'Pesantren Salafiyah (Tradisional)',
            //     'phone_number' => $faker->phoneNumber(12),
            //     'website' => 'www.' . $faker->word(7) . '.com',
            //     'email' => $faker->email,
            //        'standing_date' => $faker->date,
            //     'pimpinan' => 'Belum diisi',
            //     'surface_area' => $faker->randomNumber(4, true),
            //     'building_area' => $faker->randomNumber(4, true),
            //     'city' => 'Batang',
            //     'subdistrict' => 'Banyuputih',
            //     'postal_code' => 51271,
            //     'address' => 'Desa Kalangsono', // Address is provided
            //     'latitude' => null, // Latitude information is missing in the provided data
            //     'longitude' => null, // Longitude information is missing in the provided data
            //     'status' => 'active',
            // ],

            // Entry 20 (Miftahul Ulum)
            [
                'nspp' => '510033250055',
                'name' => 'Miftahul Ulum',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '17.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Batang',
                'postal_code' => 51216,
                'address' => 'Ds. Cepokokuning', // Address is provided
                'latitude' => -6.950434675172625,
                'longitude' => 109.74802368475002,
                'status' => 'active',
            ],

            // Entry 21 (Bardan Wassalaman)
            [
                'nspp' => '510033250056',
                'name' => 'Bardan Wassalaman',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '18.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Batang',
                'postal_code' => 51216,
                'address' => 'Kel. Sambong', // Address is provided
                'latitude' => -6.919589188273131,
                'longitude' => 109.73960232000924,
                'status' => 'active',
            ],

            // // Entry 22 (Hayatussyafi`iyyah)
            // [
            //     'nspp' => '510033250022',
            //     'name' => 'Hayatussyafi`iyyah',
            //     'category' => 'Pesantren Salafiyah (Tradisional)',
            //     'phone_number' => $faker->phoneNumber(12),
            //     'website' => 'www.' . $faker->word(7) . '.com',
            //     'email' => $faker->email,
            //        'standing_date' => $faker->date,
            //     'pimpinan' => 'Belum diisi',
            //     'surface_area' => $faker->randomNumber(4, true),
            //     'building_area' => $faker->randomNumber(4, true),
            //     'city' => 'Batang',
            //     'subdistrict' => 'Bawang',
            //     'postal_code' => 51274,
            //     'address' => 'Dukuh Bakalan Desa Sidoharjo', // Address is provided
            //     'latitude' => -7.11835164622946,
            //     'longitude' => 109.90364414243572,
            //     'status' => 'active',
            // ],

            // Entry 23 (PPS NASHRUL HUDA)
            [
                'nspp' => '510033250024',
                'name' => 'PPS NASHRUL HUDA',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '19.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bawang',
                'postal_code' => 51274,
                'address' => 'Belum diisi', // Address is missing in the provided data
                'latitude' => -7.0989175129064215,
                'longitude' => 109.96279480218732,
                'status' => 'active',
            ],

            // Entry 24 (Assasul Huda 02)
            [
                'nspp' => '510033250028',
                'name' => 'Assasul Huda 02',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '20.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bawang',
                'postal_code' => 51274,
                'address' => 'Dk. Klawen, Rt.06, Rw.03, Desa Candigugur, 51274', // Address is provided
                'latitude' => -7.109064517988396,
                'longitude' => 109.91299337786782,
                'status' => 'active',
            ],

            // Entry 25 (PONPES KHUSNUL ANWAR)
            [
                'nspp' => '510033250048',
                'name' => 'PONPES KHUSNUL ANWAR',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '21.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bawang',
                'postal_code' => 51274,
                'address' => 'Belum diisi', // Address is missing in the provided data
                'latitude' => -7.109841075641768,
                'longitude' => 109.93734804612721,
                'status' => 'active',
            ],

            // Entry 26 (ASASUL HUDA 3)
            [
                'nspp' => '510033250062',
                'name' => 'ASASUL HUDA 3',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '22.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bawang',
                'postal_code' => 51274,
                'address' => 'Belum diisi', // Address is missing in the provided data
                'latitude' => -7.108315125281292,
                'longitude' => 109.91489744168722,
                'status' => 'active',
            ],

            // Entry 27 (Nashrul Huda)
            [
                'nspp' => '510033250086',
                'name' => 'Nashrul Huda',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '23.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bawang',
                'postal_code' => 51274,
                'address' => 'Dusun Pesanggrahan Desa Sangubanyu Rt 17 RW 5', // Address is provided
                'latitude' => -7.097737516136914,
                'longitude' => 109.9623594166918,
                'status' => 'active',
            ],

            // Entry 28 (Nurul Falah)
            [
                'nspp' => '510033250089',
                'name' => 'Nurul Falah',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '24.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bawang',
                'postal_code' => 51274,
                'address' => 'Desa Surjo Rt. 010 Rw. 04 Surjo 51274', // Address is provided
                'latitude' => -7.103843772877392,
                'longitude' => 109.91915451470102,
                'status' => 'active',
            ],

            // Entry 29 (Baitul Arqom)
            // [
            //     'nspp' => '510033250115',
            //     'name' => 'Baitul Arqom',
            //     'category' => 'Pesantren Salafiyah (Tradisional)',
            //     'phone_number' => $faker->phoneNumber(12),
            //     'website' => 'www.' . $faker->word(7) . '.com',
            //     'email' => $faker->email,
            //        'standing_date' => $faker->date,
            //     'pimpinan' => 'Belum diisi',
            //     'surface_area' => $faker->randomNumber(4, true),
            //     'building_area' => $faker->randomNumber(4, true),
            //     'city' => 'Batang',
            //     'subdistrict' => 'Bawang',
            //     'postal_code' => 51274,
            //     'address' => 'Belum diisi', // Address is missing in the provided data
            //     'latitude' => null, // Latitude information is missing in the provided data
            //     'longitude' => null, // Longitude information is missing in the provided data
            //     'status' => 'active',
            // ],

            // Entry 30 (PP JLAMPRANG)
            [
                'nspp' => '510033250123',
                'name' => 'PP JLAMPRANG',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '25.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bawang',
                'postal_code' => 51274,
                'address' => 'DK. JLAMPRANG', // Address is provided
                'latitude' => -7.1115052036956605,
                'longitude' => 109.9235734104012,
                'status' => 'active',
            ],

            [
                'nspp' => '510233250077',
                'name' => 'AL KHAFIFIYAH',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '26.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bawang',
                'postal_code' => 51274,
                'address' => 'Belum diisi',
                'latitude' => -7.104137575063574,
                'longitude' => 109.91481069813578,
                'status' => 'active',
            ],
            // [
            //     'nspp' => '510333250018',
            //     'name' => 'Darussalam',
            //     'category' => 'Pesantren Salafiyah (Tradisional)',
            //     'phone_number' => $faker->phoneNumber(12),
            //     'website' => 'www.' . $faker->word(7) . '.com',
            //     'email' => $faker->email,
            //        'standing_date' => $faker->date,
            //     'pimpinan' => 'Belum diisi',
            //     'surface_area' => $faker->randomNumber(4, true),
            //     'building_area' => $faker->randomNumber(4, true),
            //     'city' => 'Batang',
            //     'subdistrict' => 'Bawang',
            //     'postal_code' => 51274,
            //     'address' => 'Belum diisi',
            //     'latitude' => null,
            //     'longitude' => null,
            //     'status' => 'active',
            // ],
            [
                'nspp' => '510333250049',
                'name' => 'PONDOK PESANTREN NURUL IMAN',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '27.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bawang',
                'postal_code' => 51274,
                'address' => 'Belum diisi',
                'latitude' => -7.099773561261527,
                'longitude' => 109.91664004946408,
                'status' => 'active',
            ],
            // [
            //     'nspp' => '510333250052',
            //     'name' => 'NURUL IMAN BAWANG',
            //     'category' => 'Pesantren Salafiyah (Tradisional)',
            //     'phone_number' => $faker->phoneNumber(12),
            //     'website' => 'www.' . $faker->word(7) . '.com',
            //     'email' => $faker->email,
            //        'standing_date' => $faker->date,
            //     'pimpinan' => 'Belum diisi',
            //     'surface_area' => $faker->randomNumber(4, true),
            //     'building_area' => $faker->randomNumber(4, true),
            //     'city' => 'Batang',
            //     'subdistrict' => 'Bawang',
            //     'postal_code' => 51274,
            //     'address' => 'Belum diisi',
            //     'latitude' => null,
            //     'longitude' => null,
            //     'status' => 'active',
            // ],
            [
                'nspp' => '510333250065',
                'name' => 'Darussalam',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '28.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Bawang',
                'postal_code' => 51274,
                'address' => 'Jl. Walisongo No. 23 Bawang',
                'latitude' => -7.104986641411139,
                'longitude' => 109.91685003655056,
                'status' => 'active',
            ],

            [
                'nspp' => '510033250013',
                'name' => 'Hidayatul Iman',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,

                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Blado',
                'postal_code' => 51255,
                'address' => 'Desa Kalipancur',
                'latitude' => -7.042791067599879,
                'longitude' => 109.84689027048235,
                'status' => 'active',
            ],
            [
                'nspp' => '510333250013',
                'name' => 'Rautdlatul Uqlu',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '30.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Blado',
                'postal_code' => 51255,
                'address' => 'Belum diisi',
                'latitude' => -7.06140498976233,
                'longitude' => 109.84324808365848,
                'status' => 'active',
            ],
            [
                'nspp' => '510333250074',
                'name' => 'Nurul Mutadlo',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '31.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Blado',
                'postal_code' => 51255,
                'address' => 'Belum diisi',
                'latitude' => -7.084849474069301,
                'longitude' => 109.84118046623253,
                'status' => 'active',
            ],
            [
                'nspp' => '510033250038',
                'name' => 'Al Hikmah',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '32.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Gringsing',
                'postal_code' => 51281,
                'address' => 'Jl Plelen - Ketanggan Km 2 Ds Sawangan',
                'latitude' => -6.9582787780854245,
                'longitude' => 109.99493606405153,
                'status' => 'active',
            ],
            [
                'nspp' => '510033250039',
                'name' => 'Al Fatah',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,

                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Gringsing',
                'postal_code' => 51281,
                'address' => 'Sambungrejo, Rt 03/ Rw 03, Sawangan',
                'latitude' => -6.963066731996134,
                'longitude' => 109.99250209322007,
                'status' => 'active',
            ],

            [
                'nspp' => '510033250058',
                'name' => 'ANNIDZOM',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '34.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Gringsing',
                'postal_code' => 51281,
                'address' => 'Belum diisi',
                'latitude' => -6.958454640350634,
                'longitude' => 110.03665973345792,
                'status' => 'active',
            ],

            [
                'nspp' => '510033250119',
                'name' => 'Pondok Persantren Al Fidyah',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '35.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Gringsing',
                'postal_code' => 51281,
                'address' => 'Jl. Raya Lama Gringsing Rt 02 Rw 07',
                'latitude' => -6.962261165176607,
                'longitude' => 110.0461536529986,
                'status' => 'active',
            ],

            [
                'nspp' => '510033250172',
                'name' => 'Al Falah',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,

                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Gringsing',
                'postal_code' => 51281,
                'address' => 'Jl. Plelen - Sawangan Km 2,5',
                'latitude' => -6.963231409923222,
                'longitude' => 109.99248304554328,
                'status' => 'active',
            ],

            [
                'nspp' => '510333250040',
                'name' => 'PP AL MUNAWWIR',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '37.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Gringsing',
                'postal_code' => 51281,
                'address' => 'JL RAYA LAMA NO 16',
                'latitude' => -6.961982681695842,
                'longitude' => 110.04628419454328,
                'status' => 'active',
            ],

            [
                'nspp' => '510033250064',
                'name' => 'Darul Ulum',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '38.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Kandeman',
                'postal_code' => 51261,
                'address' => 'Ds. Tragung',
                'latitude' => -6.943980823699606,
                'longitude' => 109.76189578239175,
                'status' => 'active',
            ],
            [
                'nspp' => '510033250111',
                'name' => 'El- Husna',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,

                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Kandeman',
                'postal_code' => 51261,
                'address' => 'Desa Bakalan Kecamatan Kandeman Kabupaten Batang',
                'latitude' => -6.930206137949526,
                'longitude' => 109.77938291038042,
                'status' => 'active',
            ],

            [
                'nspp' => '510033250125',
                'name' => 'PPTQ DARUL ULUM',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,

                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Kandeman',
                'postal_code' => 51261,
                'address' => 'Belum diisi',
                'latitude' => -6.943847696977042,
                'longitude' => 109.76133788288968,
                'status' => 'active',
            ],

            [
                'nspp' => '510033250042',
                'name' => 'Tpi Al Hidayah',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '41.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Limpung',
                'postal_code' => 51271,
                'address' => 'Plumbon Rt 06 Rw 01 Limpung Batang',
                'latitude' => -7.019957835089635,
                'longitude' => 109.93645705130928,
                'status' => 'active',
            ],

            [
                'nspp' => '510033250043',
                'name' => 'Ad Diroyah',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,

                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Limpung',
                'postal_code' => 51271,
                'address' => 'Jl.Kartika Pungangan Limpung Batang Jawa Tengah',
                'latitude' => -6.997323735215885,
                'longitude' => 109.92245570248816,
                'status' => 'active',
            ],

            [
                'nspp' => '510033250046',
                'name' => 'PP. Roudlotul Muhtadin',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '43.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Limpung',
                'postal_code' => 51271,
                'address' => 'Dlisen Rt 01 Rw 01',
                'latitude' => -7.000265163857142,
                'longitude' => 109.95341143173387,
                'status' => 'active',
            ],

            [
                'nspp' => '510033250047',
                'name' => 'Nurul Anwar',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '44.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Limpung',
                'postal_code' => 51271,
                'address' => 'Dukuh Kendayaan',
                'latitude' => -7.004280078084563,
                'longitude' => 109.94096179639698,
                'status' => 'active',
            ],

            // [
            //     'nspp' => '510033250061',
            //     'name' => 'AL MIFTAH',
            //     'category' => 'Pesantren Salafiyah (Tradisional)',
            //     'phone_number' => $faker->phoneNumber(12),
            //     'website' => 'www.' . $faker->word(7) . '.com',
            //     'email' => $faker->email,
            //        'standing_date' => $faker->date,
            //     'pimpinan' => 'Belum diisi',
            //     'surface_area' => $faker->randomNumber(4, true),
            //     'building_area' => $faker->randomNumber(4, true),
            //     'city' => 'Batang',
            //     'subdistrict' => 'Limpung',
            //     'postal_code' => 51271,
            //     'address' => 'Belum diisi',
            //     'latitude' => null,
            //     'longitude' => null,
            //     'status' => 'active',
            // ],
            [
                'nspp' => '510033250081',
                'name' => 'Ar Roudloh',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '45.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Limpung',
                'postal_code' => 51271,
                'address' => 'Jl. Syamsuri Gg. Mii Rt 03 Rw Iii Babadan',
                'latitude' => -7.011090427926833,
                'longitude' => 109.93248745581569,
                'status' => 'active',
            ],

            [
                'nspp' => '510033250085',
                'name' => 'Al Hikmah',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '46.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Limpung',
                'postal_code' => 51271,
                'address' => 'Jl. Raya Limpung-Tersono Km 02 Rt. 01 Rw. 01',
                'latitude' => -7.017199494534233,
                'longitude' => 109.93266273548117,
                'status' => 'active',
            ],
            [
                'nspp' => '510033250129',
                'name' => 'Al Aziziyah',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '47.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Limpung',
                'postal_code' => 51271,
                'address' => 'Jl. Pesantren Gg. Baidlowi Rt. 01 Rw. 01 Desa Dlisen',
                'latitude' => -7.006532419392594,
                'longitude' => 109.94278375295666,
                'status' => 'active',
            ],

            [
                'nspp' => '510033250127',
                'name' => 'Hidayatul Muhtadin',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '48.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Reban',
                'postal_code' => 51273,
                'address' => 'Desa Sukomangli Rt. 06/01 Kec. Reban 51273 Kab. Batang',
                'latitude' => -7.05417910017034,
                'longitude' => 109.90498729742983,
                'status' => 'active',
            ],
            [
                'nspp' => '510033250130',
                'name' => 'Darussalam',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '49.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Subah',
                'postal_code' => 51263,
                'address' => 'Rt 02/03 Kemiri Barat',
                'latitude' => -6.952552289229365,
                'longitude' => 109.89924838019115,
                'status' => 'active',
            ],
            [
                'nspp' => '510033250063',
                'name' => 'PONDOK PESANTREN DARUSSALAM',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,

                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Subah',
                'postal_code' => 51263,
                'address' => 'Belum diisi',
                'latitude' => -6.950934998985995,
                'longitude' => 109.89934518326139,
                'status' => 'active',
            ],
            [
                'nspp' => '510033250087',
                'name' => 'Darul Ulum',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,

                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Subah',
                'postal_code' => 51263,
                'address' => 'Belum diisi',
                'latitude' => -6.959870832731473,
                'longitude' => 109.91253441786301,
                'status' => 'active',
            ],
            [
                'nspp' => '510333250050',
                'name' => 'PONDOK PESANTREN SALAF & TAHFIZH AL - QURAN AL - HUDA',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '52.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Subah',
                'postal_code' => 51263,
                'address' => '2VWM+98W, Gunungpring, RT.08/RW.03, Gn. Pring, Gondang',
                'latitude' => -6.954016337522322,
                'longitude' => 109.8833134591748,
                'status' => 'active',
            ],
            [
                'nspp' => '510033250031',
                'name' => 'Raudhotu Firqotinnajiyah',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,

                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Tersono',

                'postal_code' => 51272,
                'address' => 'Tanjungsari, Tersono, Batang',
                'latitude' => -7.023176434161359,
                'longitude' => 109.96842145355589,
                'status' => 'active',
            ],
            // [
            //     'nspp' => '510033250069',
            //     'name' => 'SREGEP NGAJI',
            //     'category' => 'Pesantren Salafiyah (Tradisional)',
            //     'phone_number' => $faker->phoneNumber(12),
            //     'website' => 'www.' . $faker->word(7) . '.com',
            //     'email' => $faker->email,
            //        'standing_date' => $faker->date,
            //     'pimpinan' => 'Belum diisi',
            //     'surface_area' => $faker->randomNumber(4, true),
            //     'building_area' => $faker->randomNumber(4, true),
            //     'city' => 'Batang',
            //     'subdistrict' => 'Tersono',

            //     'postal_code' => 51272,
            //     'address' => 'Belum diisi',
            //     'latitude' => null,
            //     'longitude' => null,
            //     'status' => 'active',
            // ],
            [
                'nspp' => '510033250059',
                'name' => 'Ponpes Nurul Huda Pandansari',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,

                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Warungasem',
                'postal_code' => 51252,
                'address' => 'Jl. Raya Pandansari, Dk. Krajan RT 01/RW 01',
                'latitude' => -6.983710230725412,
                'longitude' => 109.72010824851375,
                'status' => 'active',
            ],
            [
                'nspp' => '510033250070',
                'name' => 'AL-INAAROH',
                'category' => 'Pesantren Salafiyah (Tradisional)',
                'phone_number' => $faker->phoneNumber(12),
                'website' => 'www.' . $faker->word(7) . '.com',
                'email' => $faker->email,
                'standing_date' => $faker->date,
                'photo_profil' => '55.jpg',
                'pimpinan' => 'Belum diisi',
                'surface_area' => $faker->randomNumber(4, true),
                'building_area' => $faker->randomNumber(4, true),
                'city' => 'Batang',
                'subdistrict' => 'Wonotunggal',
                'postal_code' => 51253,
                'address' => 'Belum diisi',
                'latitude' => -6.978826081417314,
                'longitude' => 109.74593768704092,
                'status' => 'active',
            ],

        ];

        foreach ($ponpes as $key => $value) {
            Ponpes::create($value);
        }

    }
}
